Fix  faulty object assert
Order of list can cause error

Error: 4,274 [INFO] 10:22:24,274 [ERROR] io.phasetwo.service.mapper.OrganizationRoleMapperTest.shouldConfigureOrganizationRoleOidcProtocolMapper -- Time
10:22:24,274 [INFO] org.opentest4j.AssertionFailedError: expected: <{roles=[view-organization, manage-organization], name=example}> but was: <{roles=[manage-organization, view-organization], name=example}>